---
- hosts: chef_controller
  become: yes
  tasks:
    - name: Download and install chef
      apt:
        deb: https://packages.chef.io/files/stable/chef-workstation/20.9.158/ubuntu/18.04/chef-workstation_20.9.158-1_amd64.deb
