---
- hosts: chef_controller
  become: yes
  become_user: chefuser
  gather_facts: false
  tasks:
    - name: Download chef
      shell: "wget https://packages.chef.io/files/stable/chefworkstation/0.14/ubuntu/18.04/chefworkstation_0.14.16-1_amd64.deb -P ~/"
    - name: Install chef
      shell: "dpkg -i ~/chefworkstation_0.14.16-1_amd64.deb"
