---
- hosts: chef_controller
  become: yes
  tasks:
    - name: Download and install chef
      apt:
        deb: https://packages.chef.io/files/stable/chefworkstation/0.14/ubuntu/18.04/chefworkstation_0.14.16-1_amd64.deb
