---
- hosts: cicd
  become: true

  tasks:
    - name: apt update
      shell: "apt update"
    - name: install python3
      apt:
        name: python3
        state: present
      become: yes
    - name: install pip3
      apt:
        name: python3-pip
        state: present
      become: yes
    - name: install python3-dev
      apt:
        name: python3-dev
        state: present
      become: yes
    - name: install python-setuptools
      apt:
        name: python-setuptools
        state: present
      become: yes
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - role: "nickjj.docker"
    